pipeline {
  agent {
    docker {
      image "baselua:1.0"
      args "--user jenkins-docker \
        --env TZ='America/Los_Angeles' \
      "
    }
  }

  environment {
    subdir = "."
  }

  stages {
    stage("Tests") {
      steps {
        dir(env.subdir) {
          sh "./bustedOutputHandlers/scripts/tests.sh"
        }
      }
    }
  }
  post {
    always {
      dir(env.subdir) {
        archiveArtifacts artifacts: 'bustedOutputHandlers/reports/*.xml'
        junit 'bustedOutputHandlers/reports/*.xml'
      }
    }
  }
}
