pipeline {
  agent {
    docker {
      image "baselua:1.0"
      args "--user jenkins-docker \
        --env TZ='America/Los_Angeles' \
      "
    }
  }

  environment {
    subdir = "bustedOutputHandlers"
  }

  stages {
    stage("Tests") {
      steps {
        dir(env.subdir) {
          sh "./scripts/tests.sh"
        }
      }
    }
  }
}
